server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /producer
  port: '8494'
spring:
  rabbitmq:
    username: Admin
    password: Admin
    host: localhost
    port: 5672
    queue:
      order: "queue-order"
      payment: "queue-payment"
      shipping: "queue-shipping"